<div class="formulario">
    <div class="title">
        <h2>Dashboard</h2>

    </div>
</div>
<div class="clear"></div>
<div class="dashboard">
    <div class="icons">
        <div id="main-wrapper">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel info-box panel-white">
                        <div class="panel-body">
                            <div class="info-box-stats">
                                <p class="counter"><?php echo Clients_Model_Client::getInstance()->countAll()[0]->number; ?></p>
                                <span class="info-box-title">Cantidad de Registros</span>
                            </div>
                            <div class="info-box-icon">
                                <i class="icon-users"></i>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel info-box panel-white">
                        <div class="panel-body">
                            <div class="info-box-stats">
                                <p class="counter">340,230</p>
                                <span class="info-box-title">Page views</span>
                            </div>
                            <div class="info-box-icon">
                                <i class="icon-eye"></i>
                            </div>
                            <div class="info-box-progress">
                                <div class="progress progress-xs progress-squared bs-n">
                                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="80"
                                         aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel info-box panel-white">
                        <div class="panel-body">
                            <div class="info-box-stats">
                                <p>$<span class="counter">653,000</span></p>
                                <span class="info-box-title">Monthly revenue goal</span>
                            </div>
                            <div class="info-box-icon">
                                <i class="icon-basket"></i>
                            </div>
                            <div class="info-box-progress">
                                <div class="progress progress-xs progress-squared bs-n">
                                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60"
                                         aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel info-box panel-white">
                        <div class="panel-body">
                            <div class="info-box-stats">
                                <p class="counter">47,500</p>
                                <span class="info-box-title">New emails recieved</span>
                            </div>
                            <div class="info-box-icon">
                                <i class="icon-envelope"></i>
                            </div>
                            <div class="info-box-progress">
                                <div class="progress progress-xs progress-squared bs-n">
                                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="50"
                                         aria-valuemin="0" aria-valuemax="100" style="width: 50%">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Row -->
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="panel panel-white">
                        <?PHP

                        $db = new Entities_Client();
                        $grid = new Com_Wizard_Grid();
                        $grid->title = "Cupones Generarod";
                        $grid->setIdField("CliId");
                        $grid->setQuery($db->getList());
                        $grid->setAlias(array("CliId" => "ID", "CliName" => "Nombre", "CliCi" => "C.I.", "CliCity" => "Ciudad", "CliStatus" => "Estado"));
                        $grid->setFilters(array("CliName" => get('CliName')));
                        $grid->setFilters(array("CliCi" => get('CliCi')));

                        $toolBar = new Com_Wizard_ToolBar();
                        $toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Clients/Add');
                        $toolBar->add("search", "Filtrar", null, "showHide('.filters')");
                        $toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
                        $grid->setToolBar($toolBar);

                        $grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Clients/Edit/id/_ID_');
                        $grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Clients/Delete/id/_ID_' . "':'';");

                        $grid->customField("CliStatus", array("value" => array('1' => 'Leido', '0' => 'No Leido')));

                        $grid->render();
                        ?>

                    </div>
                </div>

            </div>
            <!-- Main Wrapper -->

            <div class="clear"></div>
        </div>
        <div class="clear"></div>

    </div>