<div style="margin-top: 0px; width: 100%; text-align: center;"> <a href="https://twitter.com/ExmaBolivia"> <img
            class="alignnone wp-image-2392 size-full"
            style="margin: 0 5px; height: 30px; width: 30px;"
            src="http://exma.com.bo/wp-content/uploads/2016/09/tw.png" alt=""
            width="42" height="42"/> </a> <a href="https://www.facebook.com/EXMABolivia/"> <img
            class="alignnone wp-image-2393 size-full"
            style="margin: 0 5px; height: 30px; width: 30px;"
            src="http://exma.com.bo/wp-content/uploads/2016/09/fb.png"
            alt="" width="42" height="42"/> </a> <a href="https://www.instagram.com/exmabolivia/"> <img
            class="alignnone wp-image-2394 size-full"
            style="margin: 0 5px; height: 30px; width: 30px;"
            src="http://exma.com.bo/wp-content/uploads/2016/09/ins.png"
            alt="" width="42" height="42"/> </a> <a href="https://www.youtube.com/channel/UC2nmqAdYvEYDi34RAUmobnQ">
        <img class="alignnone wp-image-2395 size-full" style="margin: 0 5px; height: 30px; width: 30px;"
             src="http://exma.com.bo/wp-content/uploads/2016/09/you.png" alt="" width="42" height="42"/> </a> </div>
